ut-code/ut-bridge

web/src/app/chat/layout.tsx, web/src/app/chat/page.tsx, web/src/app/community/layout.tsx, web/src/app/community/page.tsx, web/src/app/login/layout.tsx, web/src/app/login/page.tsx, web/src/app/registration/layout.tsx, web/src/app/registration/page.tsx, web/src/app/settings/layout.tsx, web/src/app/settings/page.tsx
=> 各ページの下地を作成

.env.sample, server/.env, server/bun.lock, server/package.json, server/prisma/schema.prisma
=> データベースモデルを追加

.env.sample, package.json, scripts/devdb.sh
=> dev: create local db with bun dev-db

web/package.json, web/src/client.ts, web/src/lib/env.ts
=> change next to use port 5173

web/src/app/(auth)/chat/layout.tsx, web/src/app/(auth)/chat/page.tsx, web/src/app/(auth)/community/layout.tsx, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/settings/layout.tsx, web/src/app/(auth)/settings/page.tsx, web/src/app/(auth)/users/layout.tsx, web/src/app/(auth)/users/page.tsx
=> ユーザー詳細画面を作成

scripts/seed/data/users.ts, scripts/seed/index.ts, server/prisma/schema.prisma, server/routes/community.ts, server/routes/users.ts, server/zod/schema.ts, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/settings/page.tsx, web/src/app/(auth)/users/page.tsx, web/src/app/page.tsx, web/src/app/registration/page.tsx, web/src/features/auth/functions/login.ts, web/src/features/auth/functions/logout.ts
=> いくつか修正 詳しくはコミットを見てね

.gitignore, common/tsconfig.json, scripts/seed/index.ts, scripts/seed/tsconfig.json, server/tsconfig.json, tsconfig.json, web/src/app/(auth)/chat/[id]/page.tsx, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/settings/page.tsx, web/src/app/(auth)/settings/profile/page.tsx, web/src/app/(auth)/users/page.tsx, web/tsconfig.json
=> fix tsconfig

server/routes/community.ts, web/src/app/(auth)/community/page.tsx
close #****
- correctness: 読込中に前のクエリのユーザーが表示されないように
- perf: 交換留学生とページの変更のときは、即座にリクエストを飛ばすように
- feat: クエリが URL に保存されるように
- feat: 戻るボタンで 2 ページ目 -> 1ページ目 とかに戻れるように
- chore: [server] 手動で query.page をパースしないで、 zValidator に組み込む
=> enhance: community

bun.lock, common/package.json, scripts/seed/package.json, server/package.json
=> fix: @types/bun are required to be latest, making some CIs not reproducible

bun.lock, common/package.json, common/zod/schema.ts, server/index.ts, server/prisma/schema.prisma, server/routes/community.ts, server/routes/users/index.ts, server/routes/users/markers.ts, server/routes/users/me.ts, tsconfig.json, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/settings/profile/page.tsx, web/src/features/format.ts
- **feat(server): favorite and block users**
- **feat(frontend): mark and unmark users as favorite**
- **feat(frontend): filter favorite people**
closes #62 
closes #77
=> feat: favorite

web/src/app/registration/page.tsx
=> ui: prevent duplicate submission

.env.sample, server/index.ts
=> dev: set artificial network latency

biome.jsonc, web/src/app/(auth)/chat/page.tsx, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/layout.tsx, web/src/app/(auth)/settings/page.tsx, web/src/app/(auth)/settings/profile/page.tsx, web/src/app/(auth)/users/page.tsx, web/src/app/login/page.tsx, web/src/app/page.tsx, web/src/app/registration/page.tsx, web/src/components/Header.tsx, web/src/features/auth/components/GoogleLoginButton.tsx, web/src/features/auth/components/LoginBadge.tsx
=> style: use sorted classes

lefthook.yml, server/prisma/schema.prisma
- **style: run bun prisma format**
- **lefthook: run prisma format on precommit**
close #****
=> style: format prisma

web/src/app/(auth)/users/page.tsx
=> ユーザーページのUI

server/routes/community.ts, web/src/app/(auth)/community/layout.tsx, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/layout.tsx, web/src/components/Header.tsx
=> community page ui

lefthook.yml
=> fix: prisma format at precommit should be staged afterwards

.gitignore, server/routes/chat.ts, web/src/app/(auth)/chat/[id]/page.tsx, web/src/app/(auth)/chat/page.tsx, web/src/app/(auth)/layout.tsx, web/src/app/(auth)/users/page.tsx
- **hack: gitignore scripts/seed/node_modules**
- **feat: navigate to DM room from /user**
close #****
=> feat: chat ui

web/src/app/(auth)/community/page.tsx, web/src/features/user/UserCard.tsx
=> mobile ui community page

web/src/app/(auth)/users/page.tsx
=> mobile ui users page

server/auth/func.ts, server/index.ts, web/src/app/(auth)/settings/basic/page.tsx, web/src/app/(auth)/settings/language/page.tsx, web/src/app/(auth)/settings/topic/page.tsx, web/src/app/(auth)/settings/university/page.tsx, web/src/features/auth/components/LoginBadge.tsx, web/src/features/auth/providers/AuthProvider.tsx, web/src/features/chat/NotificationProvider.tsx, web/src/features/user/userProvider.tsx
=> fix unauthorized

web/src/app/(auth)/chat/page.tsx, web/src/app/(auth)/community/page.tsx, web/src/app/(auth)/users/page.tsx, web/src/app/loading.tsx, web/src/components/Loading.tsx, web/src/features/auth/providers/AuthProvider.tsx, web/src/features/user/userProvider.tsx
- **fix: loading component has centralized definition**
- **fix: users favorite and block buttons**
close #****
=> fix loading

package.json, server/routes/chat.ts, web/src/app/[locale]/(auth)/chat/page.tsx
=> fix: regression from migrating auth to header

server/routes/community.ts, web/src/app/[locale]/(auth)/community/page.tsx, web/src/features/user/UserCard.tsx, web/src/features/user/UserFormProvider.tsx
=> fix: exclude myself from /community

web/src/components/Header.tsx
=> pathname抽出方法の変更

web/src/app/[locale]/(auth)/chat/[id]/page.tsx, web/src/app/[locale]/(auth)/users/page.tsx, web/src/components/Loading.tsx
=> 162 ローディングの位置や文字を修正したい

server/routes/community.ts, web/src/app/[locale]/(auth)/community/page.tsx, web/src/features/user/UserCard.tsx
=> 168 ブロックとボタン関連の機能

common/zod/schema.ts
=> isForeignStudentに初期値を設定

web/src/app/[locale]/(auth)/community/page.tsx, web/src/app/[locale]/(auth)/layout.tsx, web/src/app/[locale]/(auth)/settings/layout.tsx, web/src/components/Footer.tsx, web/src/components/Header.tsx, web/src/components/LanguageSelectar.tsx, web/src/consts.ts, web/src/features/setting/SideNav.tsx, web/src/hooks/useNormalizedPath.ts
=> パスの正規化に関するリファクタリング

server/routes/users/index.ts, web/messages/en.json, web/messages/ja.json, web/src/app/[locale]/(auth)/chat/[id]/page.tsx, web/src/app/[locale]/(auth)/chat/page.tsx, web/src/app/[locale]/registration/page.tsx, web/src/components/Header.tsx
=> Bugfix 0326

web/src/app/[locale]/(auth)/chat/[id]/page.tsx
=> 179 チャット画面上部に参加しているメンバーを表示する

web/src/app/[locale]/page.tsx
=> 157 キャッチコピーが改行しないようにする。ヘッダーもタイトル追加

.github/workflows/test.yml, bun.lock, package.json, web/src/hooks/useNormalizedPath.test.ts
=> run test on ci

server/auth/func.ts
=> delete cookie cache

scripts/seed/data/languages.ts
=> add korean to seed

web/src/app/[locale]/(auth)/settings/contact/page.tsx
=> お問い合わせフォームを埋め込む

web/src/components/Loading.tsx, web/src/features/auth/providers/AuthProvider.tsx
=> fixed the app stuck in loading when navigating to (/auth)/* while not being logged in

web/src/components/Header.tsx
=> 220 ログイン状態によってheader logoのリンク先を変える

server/routes/community.ts
=> fix filtering not working

web/src/app/[locale]/(auth)/settings/basic/page.tsx, web/src/app/[locale]/registration/page.tsx
=> 動く系の画像をフロントで禁止する

server/routes/chat.ts, web/src/app/[locale]/(auth)/users/page.tsx
=> 221 ブロック時のチャットの挙動を修正

web/messages/en.json, web/messages/ja.json, web/src/app/[locale]/(auth)/settings/language/page.tsx, web/src/app/[locale]/registration/step2/page.tsx, web/src/features/settings/UserFormController.tsx
=> 留学生ですか？をselectタグに変更

web/src/components/Avatar.tsx
=> 181 画像のアスペクト比を一定にする

web/src/features/auth/providers/AuthProvider.tsx
=> リロードで、/に飛ばされる問題の解決

server/routes/chat.ts
=> 242 ユーザー削除後のチャットルームの不具合

server/routes/users/me.ts, web/src/app/[locale]/(auth)/settings/language/page.tsx
=> 言語を編集して登録ボタンを押しても、編集した内容は消えなくなった

web/src/app/[locale]/(auth)/chat/[id]/page.tsx
=> チャット画面で相手ユーザーの画像を表示

web/src/app/[locale]/(auth)/chat/[id]/page.tsx
=> cmd+enter or ctrl+enterでメッセージ送信

web/src/app/[locale]/(auth)/settings/basic/page.tsx, web/src/features/settings/UserFormController.tsx
=> 269 プロフィール画像を設定画面で表示&画像アップロード不具合を修正

web/src/app/[locale]/registration/step2/page.tsx
=> 273 スマホ版UIのregisterボタン

common/zod/schema.ts, web/messages/en.json, web/messages/ja.json, web/src/app/[locale]/(auth)/settings/basic/page.tsx, web/src/app/[locale]/registration/page.tsx, web/src/app/[locale]/registration/step2/page.tsx, web/src/features/settings/UserFormController.tsx
=> 239 名前を30文字に制限

web/src/app/[locale]/(auth)/chat/page.tsx
=> 275 no messagesを削除

web/src/app/[locale]/(auth)/users/page.tsx
=> 名前がはみ出ないように見境なく切る

web/src/app/[locale]/registration/page.tsx, web/src/app/[locale]/registration/step2/page.tsx
=> 211 初期登録画面でも表示言語を切り替えられる

server/routes/users/me.ts, web/src/features/settings/UserFormController.tsx
=> キャンパスとか学部の更新の修正と、関係ないバグの修正

server/routes/image.ts, web/next.config.ts
close #235
**新しいenv fileをdiscordから取得してください**
=> 235 画像をpublic accessにすることで消えないようにする

scripts/seed/dev.ts, web/next.config.ts
=> bun dbで登録される写真のドメインを修正

server/routes/users/me.ts, web/src/app/[locale]/(auth)/settings/basic/page.tsx, web/src/features/settings/UserFormController.tsx
=> fix not being able to see and update wantToMatch in settings

.gitignore, server/routes/chat.ts, web/src/app/[locale]/(auth)/chat/[id]/page.tsx
#182を部分解決。まだ編集はできていない。 
チャットが削除可能に。チャットを長押し→「削除」を選択→モーダル→削除
=> チャットメッセージ削除・編集

bun.lock, common/package.json, package.json, server/package.json, web/package.json
=> chore: update packages
